//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RMSDataAccessLayer
{
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;
    using TrackableEntities;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Runtime.Serialization;
    using System.Collections.ObjectModel;

    using System;
    using System.Collections.Generic;
    using TrackableEntities.Client;
    
    public partial class DoctorsView : BaseEntity<DoctorsView>
    {
        [DataMember]
                    [Required(ErrorMessage="Name is required")]
    	public string Name
    	{ 
    		get { return _Name; }
    		set
    		{
    			if (Equals(value, _Name)) return;
    			_Name = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private string _Name;
        [DataMember]
                    [Required(ErrorMessage="Code is required")]
    	public string Code
    	{ 
    		get { return _Code; }
    		set
    		{
    			if (Equals(value, _Code)) return;
    			_Code = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private string _Code;
        [DataMember]
                    [Required(ErrorMessage="DoctorId is required")]
    	public int DoctorId
    	{ 
    		get { return _DoctorId; }
    		set
    		{
    			if (Equals(value, _DoctorId)) return;
    			_DoctorId = value;
                ValidateModelProperty(this, value);
    			NotifyPropertyChanged();
    		}
    	}
    	private int _DoctorId;
    }
}
